name: Auto Coin Mining

on:
  schedule:
    - cron: '22 0 * * *'
  workflow_dispatch:

env:
  MINET_SID: ${{ secrets.MINET_SID }}
  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
  TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
  ACCOUNT_NAME: 'btpp03'
  MAX_ADS: '20'
  PROXY: ${{ secrets.PROXY }}

jobs:
  mine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install --no-cache-dir -r requirements.txt
      - run: xvfb-run python minet_coin.py
        env:
          DISPLAY: ':99.0'
